# Generated by Django 5.1 on 2024-08-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HeroSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "portrait_image",
                    models.ImageField(
                        help_text="Upload a portrait image for the hero section.",
                        upload_to="Media/",
                    ),
                ),
                (
                    "greeting",
                    models.CharField(
                        help_text='Greeting message, e.g., "Namasté, I\'m"',
                        max_length=255,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name to display in the hero section.", max_length=255
                    ),
                ),
                (
                    "profession",
                    models.CharField(
                        help_text='Profession or title, e.g., "Frontend Developer"',
                        max_length=255,
                    ),
                ),
                (
                    "tagline",
                    models.TextField(
                        help_text="Tagline or description for the hero section."
                    ),
                ),
                (
                    "github_link",
                    models.URLField(
                        blank=True, help_text="Link to GitHub profile.", null=True
                    ),
                ),
                (
                    "twitter_link",
                    models.URLField(
                        blank=True, help_text="Link to Twitter profile.", null=True
                    ),
                ),
                (
                    "instagram_link",
                    models.URLField(
                        blank=True, help_text="Link to Instagram profile.", null=True
                    ),
                ),
                (
                    "youtube_link",
                    models.URLField(
                        blank=True, help_text="Link to YouTube channel.", null=True
                    ),
                ),
                (
                    "linkedin_link",
                    models.URLField(
                        blank=True, help_text="Link to LinkedIn profile.", null=True
                    ),
                ),
                (
                    "discord_link",
                    models.URLField(
                        blank=True, help_text="Link to Discord server.", null=True
                    ),
                ),
                (
                    "contact_link",
                    models.URLField(help_text="Link to the contact section."),
                ),
                (
                    "portfolio_link",
                    models.URLField(help_text="Link to the portfolio section."),
                ),
            ],
        ),
    ]
