# Generated by Django 5.1 on 2024-08-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("url", models.URLField()),
                ("icon", models.ImageField(upload_to="projects/icons/")),
                ("banner", models.ImageField(upload_to="projects/banners/")),
                ("stacks", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
