# Generated by Django 5.1 on 2024-08-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="banner",
            field=models.ImageField(upload_to="Media/projects/banners/"),
        ),
        migrations.AlterField(
            model_name="project",
            name="icon",
            field=models.ImageField(upload_to="Media/projects/icons/"),
        ),
    ]
