# Generated by Django 5.1 on 2024-08-11 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_certificate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="certificate",
            name="description",
        ),
    ]
