# Generated by Django 5.1 on 2024-08-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_remove_certificate_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="description",
            field=models.TextField(max_length=300, null=True),
        ),
    ]
