# Generated by Django 5.1 on 2024-08-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_certificate_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="Media/courses/")),
                ("url", models.URLField()),
                ("tag", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
